# Generated by Django 4.0.4 on 2022-04-29 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0004_recipe")]

    operations = [
        migrations.RenameField(
            model_name="recipe", old_name="minutes", new_name="time_minutes"
        )
    ]
