# Generated by Django 4.0.4 on 2022-04-29 16:00

import core.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_rename_minutes_recipe_time_minutes")]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                null=True, upload_to=core.models.recipe_image_file_path
            ),
        )
    ]
